---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: ${namespace}
---

apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  oidc.config: |
    name: SSO
    issuer: https://keycloak.${domain}/auth/realms/${environment}
    clientID: argocd
    clientSecret: ${argo_client_secret}
    requestedScopes: ["openid", "profile", "email"]
  repositories: |
    - url: https://git.asmgmt.hilti.com/infra/packages.git
  repository.credentials: |
    - url: https://git.asmgmt.hilti.com
      usernameSecret:
        key: gitlab-repo-user
        name: argocd-secret
      passwordSecret:
        key: gitlab-repo-password
        name: argocd-secret
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /status
    extensions/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle
        - /webhooks/10/clientConfig/caBundle
  resource.exclusions: |
    - apiGroups:
      - velero.io
      kinds:
      - Backup
      clusters:
      - "*"
  statusbadge.enabled: "true"
  url: https://argo.${domain}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: ${namespace}
